name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm build
      - run: npx changeset version
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - run: git commit -m "Version packages [skip ci]" || echo "No changes to commit"
      - run: git push
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npx changeset publish
