name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: npx changeset version
      - run: git add .
      - run: git commit -m "Version packages [skip ci]" || echo "No changes to commit"
      - run: git push
      - run: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
