name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: npx changeset version
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - run: git commit -m "Version packages [skip ci]" || echo "No changes to commit"
      - run: git push
      - run: npx changeset publish
